# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_merge_20181012_1358'),
        ('videos', '0010_auto_20180830_1237'),
    ]

    operations = [
    ]
